# LoRA微调配置文件

# 模型配置
model:
  name: "Qwen/Qwen2-0.5B"  # 使用轻量级模型便于学习
  max_length: 512
  trust_remote_code: true

# LoRA配置
lora:
  r: 16                    # LoRA秩，控制参数量
  lora_alpha: 32           # LoRA缩放参数
  target_modules: ["q_proj", "v_proj", "k_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
  lora_dropout: 0.1
  bias: "none"
  task_type: "CAUSAL_LM"

# 训练配置
training:
  output_dir: "./outputs"
  num_train_epochs: 3
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 4
  learning_rate: 2e-4
  weight_decay: 0.01
  warmup_ratio: 0.1
  logging_steps: 10
  save_steps: 500
  eval_steps: 500
  save_total_limit: 2
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  fp16: true
  dataloader_num_workers: 4

# 数据配置
data:
  train_file: "data/chinese_instructions.json"
  validation_split: 0.1
  max_samples: 1000  # 限制样本数量便于快速学习

# 日志配置
logging:
  use_wandb: true
  project_name: "lora_quickstart"
  run_name: "qwen2_lora_finetune"
